FROM golang:1.24-alpine AS build
WORKDIR /src
COPY go.mod ./
RUN go mod download
COPY . .
RUN go build -o /bin/worker ./cmd/worker

FROM alpine:3.20
COPY --from=build /bin/worker /bin/worker
ENTRYPOINT ["/bin/worker"]
